[versions]
androidGradlePlugin = "8.12.3"
kotlinAndroid = "1.9.10"
compose = "1.5.3"
espressoCore = "3.5.1"
junit = "1.1.5"
junitVersion = "4.13.2"
uiautomator = "2.2.0"

[libraries]
compose-bom = "androidx.compose:compose-bom:2023.09.00"
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material = { module = "androidx.compose.material:material" }
compose-tooling-debug = { module = "androidx.compose.ui:ui-tooling" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.2"

androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
junit = { module = "junit:junit", version.ref = "junitVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }

[bundles]

